name: Deploy Jekyll site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Just
        uses: extractions/setup-just@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install additional dependencies
        run: sudo apt-get update -y && sudo apt-get install imagemagick -y
      - name: Install Node dependencies
        run: npm ci
      - name: Build
        run: just ci
        env:
          JEKYLL_ENV: production
          TZ: Pacific/Auckland
          BASEURL: ${{ steps.pages.outputs.base_path }}
      - name: Remove original gallery photos from artifact
        run: rm -f _site/assets/gallery/*.jpg
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
