name: Lint

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - run: yarn lint
      - run: yarn check-fmt
